routes/web.php
Route::get('password/edit', 'Admin\Auth\ForgotPasswordController@passworUpdateForm')->name('password.edit');
Route::post('password/update', 'Admin\Auth\ForgotPasswordController@updatePassword')->name('password.update');
Route::get('email/verification/{param}', 'Api\Payment\PaymentController@verifyEmail')->name("email.verification");
//STRIPE
Route::get('create/account/success', 'Api\Payment\PaymentController@createAccountSuccess')->name("create.account.succes");
Route::get('refresh/account/{id}', 'Api\Payment\PaymentController@refreshAccount')->name("refresh.account");
Route::get('driver/refresh/stripe/account', 'Api\Payment\PaymentController@refreshStripeAccount')->name("driver.refresh.stripe.account");

Route::get('get/stripe-balance', 'Api\Payment\PaymentController@getStripeBalance')->name("get.stripe-balance");

Route::get('driver/check/stripe/account', 'Api\Payment\PaymentController@checkStripeAccount')->name("driver.check.stripe.account");

Route::post('stripe/payment/transfer', 'Api\Payment\PaymentController@StripeTransferPayment')->name("stripe.payment.transfer");
//END STRIPE

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {
	Route::post('logout', 'Auth\LoginController@logout')->name('logout');
	Route::resource('dashboard', 'Dashboard\DashboardController');
	Route::get('dashboard/details/{id}/{param}', 'Dashboard\DashboardController@dashboardRequestDetails')->name('dashboard.details');

	Route::get('password', 'AdminController@password')->name('password');
	Route::post('password/update', 'AdminController@changePassword')->name('password.update');

	Route::get('profile', 'AdminController@profile')->name('profile');
	Route::post('profile/update', 'AdminController@profileUpdate')->name('profile.update');

	Route::resource('setting', 'Setting\SettingController');

	Route::get('privacy/policy', 'Setting\SettingController@privacyPolicy')->name('privacy.policy');
	
	Route::put('privacy-policy/update/{id}', 'Setting\SettingController@privacyPolicyUpdate')->name('privacy-policy.update');

	Route::get('privacy/policy/portuguese', 'Setting\SettingController@privacyPolicyPortuguese')->name('privacy.policy.portuguese');

	Route::put('privacy-policy/update/portuguese/{id}', 'Setting\SettingController@privacyPolicyUpdatePortuguese')->name('privacy-policy.update.portuguese');

	Route::put('settings/femalefriendly', 'Setting\SettingController@femaleFriendlyUpdate')->name('settings.femalefriendly');
	Route::get('get/femalefriendly', 'Setting\SettingController@getFemaleFriendly')->name('get.femalefriendly');

	Route::resource('document', 'Document\DocumentController');
	Route::get('document/active/{id}', 'Document\DocumentController@changeStatus')->name('document.active');

//lease...
	Route::get('lease/hourly', 'Lease\LeaseController@hourlyLease')->name('lease.hourly');
	Route::get('lease/daily', 'Lease\LeaseController@dailyLease')->name('lease.daily');
	Route::get('lease/longTime', 'Lease\LeaseController@longTimeLease')->name('lease.longTime');
	Route::get('lease/view/{id}/{param}', 'Lease\LeaseController@showLeaseDetails')->name('lease.view');

	Route::resource('service', 'Service\ServiceTypeController');

	Route::resource('vehicle', 'Vehicle\VehicleController');
	Route::post('vehicles','Vehicle\VehicleController@getVehicles')->name('dataProcessing');

	Route::resource('passenger', 'Passenger\PassengerController');
	Route::post('ajax-passenger','Passenger\PassengerController@ajaxPassenger')->name('ajax-passenger');
	
	Route::get('get/vehicle', 'Driver\DriverController@getVehicle')->name('get.vehicle');

	Route::resource('driver', 'Driver\DriverController');
	Route::post('ajax-driver','Driver\DriverController@ajaxDriver')->name('ajax-driver');

	Route::get('drivers/document/{id}', 'Driver\DriverController@listDriverDocument')->name('drivers.document');
	Route::get('drivers/service-type/{id}', 'Driver\DriverController@listDriverServiceType')->name('drivers.service-type');
	Route::get('driver/document/verification/{id}', 'Driver\DriverController@driverDocumentVerification')->name('driver.document.verification');
	Route::get('driver/activation/{id}', 'Driver\DriverController@driverActivationProcess')->name('driver.activation');
	  //review rating
	Route::get('drivers/review-rating/{id}', 'Driver\DriverController@driverRatingReview')->name('drivers.review-rating');
	Route::get('passenger/review-rating/{id}', 'Passenger\PassengerController@passengerRatingReview')->name('passenger.review-rating');

	Route::put('drivers/femalefriendly', 'Driver\DriverController@isFemaleFriendly')->name('drivers.femalefriendly');

	//report
	Route::get('request/all', 'DriveReport\DriveReportController@allRequest')->name('request.all');
	Route::post('ajax-all-request', 'DriveReport\DriveReportController@ajaxAllRequest')->name('ajax-all-request');
	Route::get('request/nofound', 'DriveReport\DriveReportController@noServiceFoundRequest')->name('request.nofound');
	Route::post('ajax-noservice-found', 'DriveReport\DriveReportController@ajaxNoServiceFoundRequest')->name('ajax-noservice-found');

	Route::get('request/rejected', 'DriveReport\DriveReportController@rejectedRequest')->name('request.rejected');
	Route::post('ajax-rejected-request', 'DriveReport\DriveReportController@ajaxRejectedRequest')->name('ajax-rejected-request');

	Route::get('request/schedule', 'DriveReport\DriveReportController@scheduleRequest')->name('request.schedule');
	Route::post('ajax-schedule-request', 'DriveReport\DriveReportController@ajaxScheduleRequest')->name('ajax-schedule-request');

	Route::get('request/details/{id}/{param}', 'DriveReport\DriveReportController@requestDetails')->name('request.details');

	//chat support
	Route::get('passenger/chat/support', 'Chat\ChatSupportController@passengerChatSupport')->name('passenger.chat.support');

	Route::post('chat/message/support', 'Chat\ChatSupportController@sendChatForSupport')->name('chat.message.support');

	Route::post('chat/message/support/get', 'Chat\ChatSupportController@getChatForSupport')->name('chat.message.support.get');

	Route::get('driver/chat/support', 'Chat\ChatSupportController@driverChatSupport')->name('driver.chat.support');

	Route::get('driver/get/byid', 'Chat\ChatSupportController@getDriver')->name('driver.get.byid');
	Route::get('passenger/get/byid', 'Chat\ChatSupportController@getPassenger')->name('passenger.get.byid');

	//make model year
	Route::get('get/admin/make', 'Driver\DriverController@getAdminMake')->name("get.admin.make");
	Route::post('get/admin/model', 'Driver\DriverController@getAdminModel')->name("get.admin.model");
	Route::post('get/admin/year', 'Driver\DriverController@getAdminYear')->name("get.admin.year");

	 //passenger trip
	Route::get('passenger/trip/history/{id}', 'Passenger\TripController@tripIndex')->name("passenger.trip.history");
	Route::post('ajax-passenger-trips', 'Passenger\TripController@ajaxPassengerTrips')->name('ajax-passenger-trips');
	Route::get('passenger/trip/history/details/{id}/{param}', 'Passenger\TripController@tripDetails')->name('passenger.trip.history.details');

	 //Driver trip
	Route::get('driver/trip/history/{id}', 'Driver\DriverTripController@tripIndex')->name("driver.trip.history");
	Route::post('ajax-driver-trips', 'Driver\DriverTripController@ajaxDriverTrips')->name('ajax-driver-trips');
	Route::get('driver/trip/history/details/{id}/{param}', 'Driver\DriverTripController@tripDetails')->name('driver.trip.history.details');
	 //transaction
	Route::get('driver/transaction/{id}', 'Transaction\TransactionController@index')->name('driver.transaction');
	Route::post('driver/transaction', 'Transaction\TransactionController@transactionPayout')->name('driver.transaction');

	Route::get('passenger/transaction/{id}', 'Transaction\TransactionController@passengerTransaction')->name('passenger.transaction');
	Route::get('passenger/transac/list', 'Transaction\TransactionController@passengerTransactionList')->name('passenger.transac.list');

	Route::get('earning/report', 'Transaction\TransactionController@adminEarning')->name('earning.report');

	Route::resource('promocode', 'Promocode\PromocodeController');

	Route::get('passenger/cancel/report', 'CancelCharge\CancelChargeController@passengerCancelReport')->name('passenger.cancel.report');
	Route::get('driver/cancel/report', 'CancelCharge\CancelChargeController@driverCancelReport')->name('driver.cancel.report');

	//report issue
	Route::get('reportIssue/driver/subject/list', 'ReportIssue\ReportController@driverSubjectList')->name('reportIssue.driver.subject.list');
	Route::post('reportIssue/driver/subject/add', 'ReportIssue\ReportController@driverSubjectAdd')->name('reportIssue.driver.subject.add');
	Route::get('reportIssue/driver/subject/edit/{id}', 'ReportIssue\ReportController@driverSubjectEdit')->name('reportIssue.driver.subject.edit');
	Route::put('reportIssue/driver/subject/update/{id}', 'ReportIssue\ReportController@driverSubjectUpdate')->name('reportIssue.driver.subject.update');
 
	Route::get('reportIssue/customer/subject/list', 'ReportIssue\ReportController@customerSubjectList')->name('reportIssue.customer.subject.list');
	Route::post('reportIssue/customer/subject/add', 'ReportIssue\ReportController@customerSubjectAdd')->name('reportIssue.customer.subject.add');
	Route::get('reportIssue/customer/subject/edit/{id}', 'ReportIssue\ReportController@customerSubjectEdit')->name('reportIssue.customer.subject.edit');
	Route::put('reportIssue/customer/subject/update/{id}', 'ReportIssue\ReportController@customerSubjectUpdate')->name('reportIssue.customer.subject.update');
 
	Route::get('reportIssue/driver/list', 'ReportIssue\ReportController@driverReportIssueList')->name('reportIssue.driver.list');
	Route::get('reportIssue/customer/list', 'ReportIssue\ReportController@customerReportIssueList')->name('reportIssue.customer.list');

app/Http/Controllers/Api/Passenger/EmergencyContactController.php
<?php

app/Http/Controllers/Api/Passenger/LeasingController.php
<?php

namespace App\Http\Controllers\Api\Passenger;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Services\LeasingService;

use Validator;



class LeasingController extends Controller
{
    public function hourlyRequest(request $request){
        try{
            $request['timeZone']=$timeZone=$request->header("timeZone");
            $rule=[
                'dateOfJourny' =>'required',
                'fromTime' => 'required',
                'toTime' => 'required',
                'services_type_id'=>'required',
                'address' => 'sometimes',
                'longitude'=>'required',
                'latitude'=>'required',
                'no_passenger'=>'required',
                'details'=>'required',
                'timeZone'=>'timeZone'
            ];
            $validator=$this->requestValidation($request->all(),$rule);
            if($validator->status=="false"){ return response(['message'=>$validator->message,"field"=>$validator->field,"data"=>(object)[],"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.VALIDATION_FAILED")],"e"=>[])],422); };
            $request->passenger_id=Auth::user()->id;


            $request->from_datetime =date('Y-m-d H:i:s',strtotime($request->dateOfJourny." ".$request->fromTime));
            $request->to_datetime =date('Y-m-d H:i:s',strtotime($request->dateOfJourny." ".$request->toTime));
            $request->lease_type="hourly";
            $LeasingService=new LeasingService();
            $LeasingServiceReturn=$LeasingService->accessCreateRequest($request);







            return response(['message'=>"Your request for lease has been sent. You will receive our Quote shortly and a staff may contact you.","data"=>(object)$LeasingServiceReturn,"errors"=>array("exception"=>["OK"],"e"=>[])],201);
        }
        catch(\Illuminate\Database\QueryException  $e){
            return response(['message'=>trans("api.SYSTEM_MESSAGE.SOMETHING_WENT_WRONG"),"data"=>(object)[],"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.DATABASE_EXCEPTION")],"e"=>$e)],500);
        }
        catch(\Illuminate\Http\Exceptions\HttpResponseException $e){
            return response(['message'=>trans("api.SYSTEM_MESSAGE.SOMETHING_WENT_WRONG"),"data"=>(object)[],"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.SOMETHING_WENT_WRONG")],"e"=>$e)],400);
        }
    }
    public function dailyRequest(request $request){
        try{
            $rule=[
                'dateOfJourny' =>'required',
                'services_type_id'=>'required',
                'address' => 'sometimes',
                'longitude'=>'required',
                'latitude'=>'required',
                'no_passenger'=>'required',
                'details'=>'required',
            ];
            $validator=$this->requestValidation($request->all(),$rule);
            if($validator->status=="false"){ return response(['message'=>$validator->message,"field"=>$validator->field,"data"=>(object)[],"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.VALIDATION_FAILED")],"e"=>[])],422); };
            $request->passenger_id=Auth::user()->id;

            //$request->from_datetime =date('Y-m-d h:m:s',strtotime($request->dateOfJourny));
            $request->lease_type="daily";
            $LeasingService=new LeasingService();
            $LeasingServiceReturn=$LeasingService->accessCreateRequest($request);

            return response(['message'=>"Your request for lease has been sent. You will receive our Quote shortly and a staff may contact you.","data"=>(object)$LeasingServiceReturn,"errors"=>array("exception"=>["OK"],"e"=>[])],201);
        }
        catch(\Illuminate\Database\QueryException  $e){
            return response(['message'=>trans("api.SYSTEM_MESSAGE.SOMETHING_WENT_WRONG"),"data"=>(object)[],"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.DATABASE_EXCEPTION")],"e"=>$e)],500);
        }
        catch(\Illuminate\Http\Exceptions\HttpResponseException $e){
            return response(['message'=>trans("api.SYSTEM_MESSAGE.SOMETHING_WENT_WRONG"),"data"=>(object)[],"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.SOMETHING_WENT_WRONG")],"e"=>$e)],400);
        }
    }
    public function longRequest(request $request){
        try{
            $rule=[
                'fromdate' =>'required',
                'todate' =>'required',
                'services_type_id'=>'required',
                'address' => 'sometimes',
                'longitude'=>'required',
                'latitude'=>'required',
                'details'=>'required',
            ];
            $validator=$this->requestValidation($request->all(),$rule);
            if($validator->status=="false"){ return response(['message'=>$validator->message,"field"=>$validator->field,"data"=>(object)[],"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.VALIDATION_FAILED")],"e"=>[])],422); };
            $request->passenger_id=Auth::user()->id;

            $request->from_datetime =date('Y-m-d H:i:s',strtotime($request->fromdate));
            $request->to_datetime =date('Y-m-d H:i:s',strtotime($request->todate));
            $request->lease_type="longTime";
            $request->no_passenger=0;
            $LeasingService=new LeasingService();
            $LeasingServiceReturn=$LeasingService->accessCreateRequest($request);

            return response(['message'=>"Your request for lease has been sent. You will receive our Quote shortly and a staff may contact you.","data"=>(object)$LeasingServiceReturn,"errors"=>array("exception"=>["OK"],"e"=>[])],201);
        }
        catch(\Illuminate\Database\QueryException  $e){
            return response(['message'=>trans("api.SYSTEM_MESSAGE.SOMETHING_WENT_WRONG"),"data"=>(object)[],"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.DATABASE_EXCEPTION")],"e"=>$e)],500);
        }
        catch(\Illuminate\Http\Exceptions\HttpResponseException $e){
            return response(['message'=>trans("api.SYSTEM_MESSAGE.SOMETHING_WENT_WRONG"),"data"=>(object)[],"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.SOMETHING_WENT_WRONG")],"e"=>$e)],400);
        }
    }
}

resources/views/admin/passenger/create.blade.php
@extends('admin.layout.base')

@section('title', 'Add Passenger ')

@section('content')

<div class="content-area py-1">
    <div class="container-fluid">
    	<div class="box box-block bg-white">
    	    <a href="{{ route('admin.passenger.index') }}" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> Back</a>

			<h5 style="margin-bottom: 2em;">Add Passenger</h5>

            <form class="form-horizontal" action="{{route('admin.passenger.store' )}}" method="POST" enctype="multipart/form-data" role="form">
            	{{csrf_field()}}
            	
				<div class="form-group row">
					<label for="first_name" class="col-xs-2 col-form-label">First Name</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" name="first_name" value="{{ old('first_name') }}"  id="first_name" placeholder="First Name" required>
					</div>
				</div>

				<div class="form-group row">
					<label for="last_name" class="col-xs-2 col-form-label">Last Name</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" name="last_name" value="{{ old('last_name') }}" id="last_name" placeholder="Last Name" required>
					</div>
				</div>

				<div class="form-group row">
					<label for="email" class="col-xs-2 col-form-label">Email</label>
					<div class="col-xs-10">
						<input class="form-control" type="email" name="email" value="{{ old('email') }}" id="email" placeholder="Email">
					</div>
				</div>

				<div class="form-group row">
					<label for="picture" class="col-xs-2 col-form-label">Picture</label>
					<div class="col-xs-10">
						<input type="file" accept="image/*" name="picture" class="dropify form-control-file" id="picture" aria-describedby="fileHelp">
					</div>
				</div>
				
				<div class="form-group row">
					<label for="mobile_no" class="col-xs-2 col-form-label">Mobile</label>
					<div class="col-xs-10">
						<input class="form-control" type="tel" name="mobile_no" id="mobile_no" placeholder="Mobile No" required>
						<input type="hidden" name="code" id="code">
					</div>
				</div>

				<div class="form-group row">
					<label for="dob" class="col-xs-2 col-form-label">Date of Birth</label>
					<div class="col-xs-10">
						<input class="form-control" type="date" name="dob" value="{{ old('dob') }}" id="dob">
					</div>
				</div>
				<div class="form-group row">
					<label for="gender" class="col-xs-2 col-form-label">Gender</label>
					<div class="col-xs-10">
						<input type="radio" id="Male" name="gender" value="Male">
						<label for="Male">Male</label><br>
						<input type="radio" id="Female" name="gender" value="Female">
						<label for="Female">Female</label>
					</div>
				</div>

				<div class="form-group row password">
					<label for="password" class="col-xs-2 col-form-label">Password</label>
					<div class="col-xs-10">
						<input class="form-control" type="password" name="password" id="password" placeholder="Password" required>
					</div>
				</div>
				<div class="form-group row">
					<label for="password_confirmation" class="col-xs-2 col-form-label">Password Confirmation</label>
					<div class="col-xs-10">
						<input class="form-control" type="password" name="password_confirmation" value="{{ old('password_confirmation') }}" id="password_confirmation" placeholder="Re-type Password">
					</div>
				</div>

				<div class="form-group row">
					<label for="zipcode" class="col-xs-2 col-form-label"></label>
					<div class="col-xs-10">
						<button type="submit" class="btn btn-primary">Add Passenger</button>
						<a href="{{route('admin.passenger.index')}}" class="btn btn-default">Cancel</a>
					</div>
				</div>
			</form>
		</div>
    </div>
</div>
<style type="text/css">.iti { width: 100%; }</style>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
 <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/16.0.15/css/intlTelInput.css">
 <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/16.0.15/js/intlTelInput-jquery.min.js"></script>
 <script>
	jq = jQuery.noConflict();
    use :
   		var s = jq("#mobile_no").intlTelInput({
			autoPlaceholder: 'polite',
   			separateDialCode: true,
   			formatOnDisplay: true,
   			initialCountry: 'ng',
   			preferredCountries:["ng"]
   		});

   	insteadof :
   		var d = jq("#mobile_no").intlTelInput("getSelectedCountryData").dialCode;
   		jq("#code").val(d);
		jq(document).on('countrychange', function (e, countryData) {
        	jq("#code").val((jq("#mobile_no").intlTelInput("getSelectedCountryData").dialCode));
    	});
</script>
@endsection

resources/views/admin/passenger/index.blade.php
@extends('admin.layout.base')

@section('title', 'Passengers ')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5 class="mb-1">
                Passengers
            </h5>
            <a href="{{ route('admin.passenger.create') }}" style="margin-left: 1em;" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Add New passenger</a>
            <table class="table table-striped table-bordered dataTable" id="table-pass">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Passenger Name</th>
                      {{--   <th>Last Name</th> --}}
                        <th>Email</th>
                        <th>Mobile</th>
                        <th>Action</th>
                    </tr>
                </thead>
                {{-- <tbody>
                    @foreach($passengers as $index => $passenger)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $passenger->first_name }}</td>
                        <td>{{ $passenger->last_name }}</td>
                        <td>{{ $passenger->email }}</td>
                        <td>{{ $passenger->mobile }}</td>
                        @if($passenger->passenger_profile != null)
                        <td>{{ $passenger->passenger_profile->rating }}</td>
                        @else
                        <td></td>
                        @endif
                        <td>
                            <a href="{{ route('admin.passenger.edit', $passenger->id) }}" class="btn btn-info"><i class="fa fa-pencil"></i> Edit</a>
                            <form action="{{ route('admin.passenger.destroy', $passenger->id) }}" method="POST">
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="DELETE">
                                <button class="btn btn-danger" onclick="return confirm('Are you sure?')"><i class="fa fa-trash"></i> Delete</button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody> --}}
                <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Passenger Name</th>
                        {{-- <th>Last Name</th> --}}
                        <th>Email</th>
                        <th>Mobile</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
@endsection
@section('scripts')
    <script>
        $('#table-pass').DataTable( {
            "order": [[0, 'desc']],
            "processing": true,
            "serverSide": true,
            "ajax": {
                "url":"{{route('admin.ajax-passenger')}}",
                "dataType":"json",
                "type":"POST",
                "data":{"_token":"<?= csrf_token() ?>"}
            },
            "columns":[
                {"data":"id"},
                {"data":"passenger_name"},
                {"data":"email"},
                {"data":"mobile"},
                {"data":"action","searchable":false,"orderable":false}
            ],
            responsive: true,
            dom: 'Bfrtip',
            buttons: [
                'copyHtml5',
                'excelHtml5',
                'csvHtml5',
                'pdfHtml5'
            ],
        } );
    </script>
@endsection

resources/views/admin/passenger/trip-history.blade.php
@extends('admin.layout.base')

@section('title', 'Trip History ')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5 class="mb-1">Trip History</h5>
            <a href="{{ route('admin.passenger.index') }}" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> Back</a>

            <table class="table table-striped table-bordered dataTable" id="table-triphistory">
                <thead>
                    <tr>
                        <th>Customer Name</th>
                        <th>Booking Number</th>
                        <th>Payment Method</th>
                        <th>Booking Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Customer Name</th>
                        <th>Booking Number</th>
                        <th>Payment Method</th>
                        <th>Booking Status</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script>
    $(document).ready(function(){
        var id = {{$id}};
        $('#table-triphistory').DataTable({
            "processing": true,
            "serverSide": true,
            "ajax": {
                "url":"{{route('admin.ajax-passenger-trips')}}",
                "dataType":"json",
                "type":"POST",
                "data":{ "_token":"<?= csrf_token() ?>",'id': id },
            },
            "columns":[
                {"data":"customer_name"},
                {"data":"booking_number"},
                {"data":"payment_method"},
                {"data":"booking_status"},
                {"data":"action","searchable":false,"orderable":false}
            ],
            responsive: true,
            dom: 'Bfrtip',
            buttons: [
                'copyHtml5',
                'excelHtml5',
                'csvHtml5',
                'pdfHtml5'
            ],
        });
    });
</script>
@endsection