routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('/login');
Route::get('/', 'Admin\Auth\LoginController@showLoginForm')->name('/');
Route::post('/loggedin', 'Admin\Auth\LoginController@login');
Route::get('/password/reset', 'Admin\Auth\ForgotPasswordController@otpRequestForm')->name('password.reset');
Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendOTP')->name('password.email');
Route::get('password/otp', 'Admin\Auth\ForgotPasswordController@otpForm')->name('password.otp');
Route::get('password/otpvarify', 'Admin\Auth\ForgotPasswordController@otpVarification')->name('password.otpvarify');
Route::get('password/edit', 'Admin\Auth\ForgotPasswordController@passworUpdateForm')->name('password.edit');
Route::post('password/update', 'Admin\Auth\ForgotPasswordController@updatePassword')->name('password.update');
Route::get('email/verification/{param}', 'Api\Payment\PaymentController@verifyEmail')->name("email.verification");
//STRIPE
Route::get('create/account/success', 'Api\Payment\PaymentController@createAccountSuccess')->name("create.account.succes");
Route::get('refresh/account/{id}', 'Api\Payment\PaymentController@refreshAccount')->name("refresh.account");
Route::get('driver/refresh/stripe/account', 'Api\Payment\PaymentController@refreshStripeAccount')->name("driver.refresh.stripe.account");

Route::get('get/stripe-balance', 'Api\Payment\PaymentController@getStripeBalance')->name("get.stripe-balance");

Route::get('driver/check/stripe/account', 'Api\Payment\PaymentController@checkStripeAccount')->name("driver.check.stripe.account");

Route::post('stripe/payment/transfer', 'Api\Payment\PaymentController@StripeTransferPayment')->name("stripe.payment.transfer");
//END STRIPE

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {
	Route::post('logout', 'Auth\LoginController@logout')->name('logout');
	Route::resource('dashboard', 'Dashboard\DashboardController');
	Route::get('dashboard/details/{id}/{param}', 'Dashboard\DashboardController@dashboardRequestDetails')->name('dashboard.details');

	Route::get('password', 'AdminController@password')->name('password');
	Route::post('password/update', 'AdminController@changePassword')->name('password.update');

	Route::get('profile', 'AdminController@profile')->name('profile');
	Route::post('profile/update', 'AdminController@profileUpdate')->name('profile.update');

	Route::resource('setting', 'Setting\SettingController');

	Route::get('privacy/policy', 'Setting\SettingController@privacyPolicy')->name('privacy.policy');
	
	Route::put('privacy-policy/update/{id}', 'Setting\SettingController@privacyPolicyUpdate')->name('privacy-policy.update');

	Route::get('privacy/policy/portuguese', 'Setting\SettingController@privacyPolicyPortuguese')->name('privacy.policy.portuguese');

	Route::put('privacy-policy/update/portuguese/{id}', 'Setting\SettingController@privacyPolicyUpdatePortuguese')->name('privacy-policy.update.portuguese');

	Route::put('settings/femalefriendly', 'Setting\SettingController@femaleFriendlyUpdate')->name('settings.femalefriendly');
	Route::get('get/femalefriendly', 'Setting\SettingController@getFemaleFriendly')->name('get.femalefriendly');

	Route::resource('document', 'Document\DocumentController');
	Route::get('document/active/{id}', 'Document\DocumentController@changeStatus')->name('document.active');

//lease...
	Route::get('lease/hourly', 'Lease\LeaseController@hourlyLease')->name('lease.hourly');
	Route::get('lease/daily', 'Lease\LeaseController@dailyLease')->name('lease.daily');
	Route::get('lease/longTime', 'Lease\LeaseController@longTimeLease')->name('lease.longTime');
	Route::get('lease/view/{id}/{param}', 'Lease\LeaseController@showLeaseDetails')->name('lease.view');

	Route::resource('service', 'Service\ServiceTypeController');

	Route::resource('vehicle', 'Vehicle\VehicleController');
	Route::post('vehicles','Vehicle\VehicleController@getVehicles')->name('dataProcessing');

	Route::resource('passenger', 'Passenger\PassengerController');
	Route::post('ajax-passenger','Passenger\PassengerController@ajaxPassenger')->name('ajax-passenger');
	
	Route::get('get/vehicle', 'Driver\DriverController@getVehicle')->name('get.vehicle');

	Route::resource('driver', 'Driver\DriverController');
	Route::post('ajax-driver','Driver\DriverController@ajaxDriver')->name('ajax-driver');

	Route::get('drivers/document/{id}', 'Driver\DriverController@listDriverDocument')->name('drivers.document');
	Route::get('drivers/service-type/{id}', 'Driver\DriverController@listDriverServiceType')->name('drivers.service-type');
	Route::get('driver/document/verification/{id}', 'Driver\DriverController@driverDocumentVerification')->name('driver.document.verification');
	Route::get('driver/activation/{id}', 'Driver\DriverController@driverActivationProcess')->name('driver.activation');
	  //review rating
	Route::get('drivers/review-rating/{id}', 'Driver\DriverController@driverRatingReview')->name('drivers.review-rating');
	Route::get('passenger/review-rating/{id}', 'Passenger\PassengerController@passengerRatingReview')->name('passenger.review-rating');

	Route::put('drivers/femalefriendly', 'Driver\DriverController@isFemaleFriendly')->name('drivers.femalefriendly');

	//report
	Route::get('request/all', 'DriveReport\DriveReportController@allRequest')->name('request.all');
	Route::post('ajax-all-request', 'DriveReport\DriveReportController@ajaxAllRequest')->name('ajax-all-request');
	Route::get('request/nofound', 'DriveReport\DriveReportController@noServiceFoundRequest')->name('request.nofound');
	Route::post('ajax-noservice-found', 'DriveReport\DriveReportController@ajaxNoServiceFoundRequest')->name('ajax-noservice-found');

	Route::get('request/rejected', 'DriveReport\DriveReportController@rejectedRequest')->name('request.rejected');
	Route::post('ajax-rejected-request', 'DriveReport\DriveReportController@ajaxRejectedRequest')->name('ajax-rejected-request');

	Route::get('request/schedule', 'DriveReport\DriveReportController@scheduleRequest')->name('request.schedule');
	Route::post('ajax-schedule-request', 'DriveReport\DriveReportController@ajaxScheduleRequest')->name('ajax-schedule-request');

	Route::get('request/details/{id}/{param}', 'DriveReport\DriveReportController@requestDetails')->name('request.details');

	//chat support
	Route::get('passenger/chat/support', 'Chat\ChatSupportController@passengerChatSupport')->name('passenger.chat.support');

	Route::post('chat/message/support', 'Chat\ChatSupportController@sendChatForSupport')->name('chat.message.support');

	Route::post('chat/message/support/get', 'Chat\ChatSupportController@getChatForSupport')->name('chat.message.support.get');

	Route::get('driver/chat/support', 'Chat\ChatSupportController@driverChatSupport')->name('driver.chat.support');

	Route::get('driver/get/byid', 'Chat\ChatSupportController@getDriver')->name('driver.get.byid');
	Route::get('passenger/get/byid', 'Chat\ChatSupportController@getPassenger')->name('passenger.get.byid');

	//make model year
	Route::get('get/admin/make', 'Driver\DriverController@getAdminMake')->name("get.admin.make");
	Route::post('get/admin/model', 'Driver\DriverController@getAdminModel')->name("get.admin.model");
	Route::post('get/admin/year', 'Driver\DriverController@getAdminYear')->name("get.admin.year");

	 //passenger trip
	Route::get('passenger/trip/history/{id}', 'Passenger\TripController@tripIndex')->name("passenger.trip.history");
	Route::post('ajax-passenger-trips', 'Passenger\TripController@ajaxPassengerTrips')->name('ajax-passenger-trips');
	Route::get('passenger/trip/history/details/{id}/{param}', 'Passenger\TripController@tripDetails')->name('passenger.trip.history.details');

	 //Driver trip
	Route::get('driver/trip/history/{id}', 'Driver\DriverTripController@tripIndex')->name("driver.trip.history");
	Route::post('ajax-driver-trips', 'Driver\DriverTripController@ajaxDriverTrips')->name('ajax-driver-trips');
	Route::get('driver/trip/history/details/{id}/{param}', 'Driver\DriverTripController@tripDetails')->name('driver.trip.history.details');
	 //transaction
	Route::get('driver/transaction/{id}', 'Transaction\TransactionController@index')->name('driver.transaction');
	Route::post('driver/transaction', 'Transaction\TransactionController@transactionPayout')->name('driver.transaction');

	Route::get('passenger/transaction/{id}', 'Transaction\TransactionController@passengerTransaction')->name('passenger.transaction');
	Route::get('passenger/transac/list', 'Transaction\TransactionController@passengerTransactionList')->name('passenger.transac.list');

	Route::get('earning/report', 'Transaction\TransactionController@adminEarning')->name('earning.report');

	Route::resource('promocode', 'Promocode\PromocodeController');

	Route::get('passenger/cancel/report', 'CancelCharge\CancelChargeController@passengerCancelReport')->name('passenger.cancel.report');
	Route::get('driver/cancel/report', 'CancelCharge\CancelChargeController@driverCancelReport')->name('driver.cancel.report');

	//report issue
	Route::get('reportIssue/driver/subject/list', 'ReportIssue\ReportController@driverSubjectList')->name('reportIssue.driver.subject.list');
	Route::post('reportIssue/driver/subject/add', 'ReportIssue\ReportController@driverSubjectAdd')->name('reportIssue.driver.subject.add');
	Route::get('reportIssue/driver/subject/edit/{id}', 'ReportIssue\ReportController@driverSubjectEdit')->name('reportIssue.driver.subject.edit');

resources/views/admin/include/footer.blade.php
<footer class="footer">
	<div class="container-fluid">
		<div class="row text-xs-center">
			<div class="col-sm-4 text-sm-left mb-0-5 mb-sm-0">
				<p>
                {{ App\Http\Controllers\Controller::setting()[4]->value }}
                </p>
			</div>
		</div>
	</div>
</footer>

resources/views/admin/include/header.blade.php
<!-- Header -->
<div class="site-header">
	<nav class="navbar navbar-light">
		<div class="navbar-left">
			<a class="navbar-brand" href="{{url('admin/dashboard')}}">
			<img class="image" src="{{URL::asset(App\Http\Controllers\Controller::setting()[1]->value)}}" style="height: 100%; width: auto;">
			</a>
			<div class="toggle-button light sidebar-toggle-first float-xs-left hidden-md-up">
				<span class="hamburger"></span>
			</div>
			<div class="toggle-button-second dark float-xs-right hidden-md-up">
				<i class="ti-arrow-left"></i>
			</div>
			<div class="toggle-button dark float-xs-right hidden-md-up" data-toggle="collapse" data-target="#collapse-1">
				<span class="more"></span>
			</div>
		</div>
		<div class="navbar-right navbar-toggleable-sm collapse" id="collapse-1">
			<div class="toggle-button light sidebar-toggle-second float-xs-left hidden-sm-down">
				<span class="hamburger"></span>
			</div>

			<ul class="nav navbar-nav">
				<li class="nav-item hidden-sm-down">
					<a class="nav-link toggle-fullscreen" href="javascript:void(0)">
						<i class="ti-fullscreen"></i>
					</a>
				</li>
			</ul>
			<ul class="nav navbar-nav float-md-right">
				<li class="nav-item dropdown hidden-sm-down">
					<a href="#" data-toggle="dropdown" aria-expanded="false">
						{{Auth::user()->admin_profile->first_name}}
						<span class="avatar box-48">

						@if(isset(Auth::user()->admin_profile->picture))
	                    	@if(File::exists(storage_path('app/public' .str_replace("storage", "", Auth::user()->admin_profile->picture))))
                                <img src="{{URL::asset(Auth::user()->admin_profile->picture)}}" style="height: 100%;">
                            @else
                                <img src="{{URL::asset('main/avatar.jpg')}}">
                            @endif
	                   	@else
                     		<img src="{{URL::asset('main/avatar.jpg')}}">
	                    @endif
						</span>
					</a>
					<div class="dropdown-menu dropdown-menu-right animated fadeInUp">
						<a class="dropdown-item" href="{{route('admin.profile')}}">
							<i class="ti-user mr-0-5"></i> Profile
						</a>
						<a class="dropdown-item" href="{{route('admin.password')}}">
							<i class="ti-settings mr-0-5"></i> Change Password
						</a>
						<div class="dropdown-divider"></div>

						<a class="dropdown-item" href="{{ route('admin.logout') }}" onclick="event.preventDefault(); document.getElementById('logout_form').submit();">
							<i class="ti-power-off mr-0-5"></i> Sign out</a>
						<form id="logout_form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                    	{{ csrf_field() }}
                		</form>

					</div>
				</li>
			</ul>

		</div>
	</nav>
</div>

resources/views/admin/include/nav.blade.php
<div class="site-sidebar">
	<div class="custom-scroll custom-scroll-light">
		<ul class="sidebar-menu">
			<li class="menu-title">Admin Dashboard</li>
			<li>
				<a href="{{ route('admin.dashboard.index') }}" class="waves-effect waves-light">
					<span class="s-icon"><i class="fas fa-tachometer-alt"></i></span>
					<span class="s-text">Dashboard</span>
				</a>
			</li>

			<li class="menu-title">Members</li>
			<li class="with-sub">
				<a href="javascript:void(0)" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="fas fa-user-alt"></i></span>
					<span class="s-text">Passengers</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.passenger.index') }}">List Passengers</a></li>
					<li><a href="{{ route('admin.passenger.create') }}">Add New Passenger</a></li>
				</ul>
			</li>

			<li class="with-sub">
				<a href="javascript:void(0)" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="fas fa-user-alt"></i></span>
					<span class="s-text">Drivers</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.driver.index') }}">List Drivers</a></li>
					<li><a href="{{ route('admin.driver.create') }}">Add New Driver</a></li>
				</ul>
			</li>

			<li class="menu-title">General</li>
			<li class="with-sub">
				<a href="javascript:void(0)" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="fa fa-bar-chart" aria-hidden="true"></i></span>
					<span class="s-text">Report</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.request.all') }}">All Request</a></li>
					<li><a href="{{ route('admin.request.nofound') }}">No Service Found</a></li>
					<li><a href="{{ route('admin.request.rejected') }}">Rejected Request</a></li>
					<li><a href="{{ route('admin.request.schedule') }}">Scheduled Request</a></li>
					<li><a href="{{ route('admin.passenger.cancel.report') }}">Cancel By Passenger</a></li>
					<li><a href="{{ route('admin.driver.cancel.report') }}">Cancel By Driver</a></li>
					<li><a href="{{ route('admin.earning.report') }}">Admin Earning</a></li>
				</ul>
			</li>
			<li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-car"></i></span>
					<span class="s-text">Vehicle</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.vehicle.index') }}">List Vehicles</a></li>
					<li><a href="{{ route('admin.vehicle.create') }}">Add New Vehicle</a></li>
				</ul>
			</li>

			<li class="with-sub">
				<a href="javascript:void(0)" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-view-grid"></i></span>
					<span class="s-text">Service Types</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.service.index') }}">List Service Types</a></li>
					<li><a href="{{ route('admin.service.create') }}">Add New Service Type</a></li>
				</ul>
			</li>
			<li class="with-sub">
				<a href="javascript:void(0)" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-layout-tab"></i></span>
					<span class="s-text">Documents</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.document.index') }}">List Documents</a></li>
					<li><a href="{{ route('admin.document.create') }}">Add New Document</a></li>
				</ul>
			</li>

			<li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-layout-tab"></i></span>
					<span class="s-text">Promocodes</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.promocode.index') }}">List Promocodes</a></li>
					<li><a href="{{ route('admin.promocode.create') }}">Add New Promocode</a></li>
				</ul>
			</li>

			<li class="with-sub">
				<a href="javascript:void(0)" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-layout-tab"></i></span>
					<span class="s-text">Report an issue</span>
				</a>
				<ul>
					<li class="with-sub">
						<a href="javascript:void(0)" class="waves-effect  waves-light">
							{{-- <span class="s-icon"><i class="ti-layout-tab"></i></span> --}}
							<span class="s-text">Create Subject ?</span>
							<span class="s-caret" style="float: right;"><i class="fa fa-angle-down"></i></span>
						</a>
						<ul>
							<li><a href="{{route('admin.reportIssue.customer.subject.list')}}">Passenger</a></li>
							<li><a href="{{route('admin.reportIssue.driver.subject.list')}}">Driver</a></li>
						</ul>
					</li>
					<li class="with-sub">
						<a href="javascript:void(0)" class="waves-effect  waves-light">
							{{-- <span class="s-icon"><i class="ti-layout-tab"></i></span> --}}
							<span class="s-text">View Report an issue</span>
							<span class="s-caret" style="float: right;"><i class="fa fa-angle-down"></i></span>
						</a>
						<ul>
							<li><a href="{{route('admin.reportIssue.customer.list')}}">By Passenger</a></li>
							<li><a href="{{route('admin.reportIssue.driver.list')}}">By Driver</a></li>
						</ul>
					</li>
				</ul>
			</li>

			
			<li class="menu-title">Settings</li>
			<li>
				<a href="{{ route('admin.setting.index') }}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-settings"></i></span>
					<span class="s-text">Site Settings</span>
				</a>
			</li>

			<li class="menu-title">Others</li>
			
			<li class="with-sub">
				<a href="javascript:void(0)" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="fa fa-file-text" aria-hidden="true"></i></span>
					<span class="s-text">CMS Management</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.privacy.policy') }}">English</a></li>
					<li><a href="{{ route('admin.privacy.policy.portuguese') }}">Portuguese</a></li>
				</ul>
			</li>

			<li class="menu-title">Account</li>
			<li>
				<a href="{{ route('admin.profile') }}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="fa fa-wrench" aria-hidden="true"></i></span>
					<span class="s-text">Account Settings</span>
				</a>
			</li>
			<li>
				<a href="{{ route('admin.password') }}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="fa fa-key" aria-hidden="true"></i></span>
					<span class="s-text">Change Password</span>
				</a>
			</li>
			<li class="compact-hide">
				<a href="{{ url('/admin/logout') }}"
                            onclick="event.preventDefault();
                                     document.getElementById('logout-form').submit();">
					<span class="s-icon"><i class="ti-power-off"></i></span>
					<span class="s-text">Logout</span>
                </a>

                <form id="logout-form" action="{{ url('/admin/logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
			</li>

		</ul>
	</div>
</div>